# Generated by Django 5.2 on 2025-04-14 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=255, verbose_name='Access Key')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Secret Key')),
                ('bucket_name', models.CharField(max_length=255, verbose_name='Bucket Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AWS Configuration',
                'verbose_name_plural': 'AWS Configuration',
            },
        ),
        migrations.CreateModel(
            name='DicomConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(max_length=100, verbose_name='AE Title')),
                ('port_number', models.IntegerField(verbose_name='Port Number')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Configuration',
                'verbose_name_plural': 'DICOM Configuration',
            },
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('s3_object_key', models.CharField(max_length=512)),
                ('patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_instance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('series_instance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(blank=True, max_length=16, null=True)),
                ('study_description', models.CharField(blank=True, max_length=255, null=True)),
                ('series_description', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'DICOM File',
                'verbose_name_plural': 'DICOM Files',
            },
        ),
    ]
